---
  - name: Download Golang binary
    get_url:
      url: "https://go.dev/dl/go1.22.5.linux-amd64.tar.gz"
      dest: /tmp/golang.tar.gz

  - name: Extract Golang tarball
    unarchive:
      src: /tmp/golang.tar.gz
      dest: /usr/local
      remote_src: yes

  - name: Create symlink for golang binary
    file:
      src: /usr/local/go/bin/go
      dest: /usr/local/bin/go
      state: link

  - name: Clean up
    file:
      path: /tmp/golang.tar.gz
      state: absent
